services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redirect_serv_app
    env_file:
      - .env
    environment:
      SQL_HOST: ${POSTGRES_HOST}
      SQL_PORT: ${POSTGRES_PORT}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - lya_network
    expose:
      - "8000"

networks:
  lya_network:
    name: lya_network
    external: true
