services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redirect_serv_app
    env_file:
      - .env
    environment:
      SQL_HOST: ${POSTGRES_HOST}
      SQL_PORT: ${POSTGRES_PORT}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - lya_network

  nginx:
    image: nginx:alpine
    container_name: redirect_serv_nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - lya_network

networks:
  lya_network:
    name: lya_network
    external: true
